### ISSUE TITLE
Difference in Salutation data from Contact View and Export View [D7]

### ISSUE THREAD

**Issue by blackmsith** [Maott/test#17]
<p>Check Salutation field, it is &#39;Ms&#39; in Contact page where as &#39;Frau&#39; in Export View.</p><p>Also, the grabbed data is disappeared, once the field is edited. OneDrive Link to Gif: <a href="https://snapaddy-my.sharepoint.com/:i:/p/s_blacksmith/ETVUyaAEAu9MigqJYMlFNSsBkHkccNUmAxBg7wXzOUiroQ?e=RCXNPF">https://snapaddy-my.sharepoint.com/:i:/p/s_blacksmith/ETVUyaAEAu9MigqJYMlFNSsBkHkccNUmAxBg7wXzOUiroQ?e=RCXNPF</a></p><p>rthrthrh</p>

**Comment by blackmsith** [comment]
`Created by TestQuality - Linked to TestQuality.com defect D7. Do not remove or edit.` [D7](https://snapaddy.testquality.com/project/1475/result/994503/defect/3559)

**Comment by Maott** [comment]
<p>This is no bug.</p><p>We use this function in the mapping:</p><p>&nbsp; &nbsp; &quot;salutationFunction&quot;: &quot;if(address.gender === 0) { return &#39;Herr&#39;; } else if (address.gender === 1){ return &#39;Frau&#39;; } else { return &#39;&#39;; }&quot;</p><p><br></p><p>User has to decide which value he wants to be exported to the Salutation field and then we can change it in the mapping.</p>
